### ISSUE TITLE
No implementation found for method withPrivacyPolicy / show

### ISSUE THREAD

**Issue by wszak** [cleveradssolutions/CAS-Flutter#20]
This code:
```
        _consentFlow = CAS.buildConsentFlow()
          .withDismissListener(this)
          .withPrivacyPolicy(privacyUrl);
```

produces:

```
logError handler error MissingPluginException(No implementation found for method withPrivacyPolicy on channel com.cleveradssolutions.plugin.flutter/manager_builder)
I/flutter ( 3207): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
I/flutter ( 3207): <asynchronous suspension>
```

Whereas this code:
```
await _consentFlow.show();
```

produces:

```
logError handler error PlatformException(MethodCallArgumentNull, Method: 'show', error: argument 'force' is null, null, null)
I/flutter ( 3207): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
I/flutter ( 3207): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
I/flutter ( 3207): <asynchronous suspension>
```

Tried lib 0.6.0 + 3.9.5, and 0.6.1 + 3.9.6

Also in this code from your example. What `status`  values mean?
```
class DismissListenerWrapper extends OnDismissListener {
  @override
  onConsentFlowDismissed(int status) {
  }
}
```

**Comment by kraativ** [comment]
Thank you for the detailed issue description, it has been fixed in version 0.6.2.
The status descriptions have been added to the ConsentFlow class.
